# SPDX-License-Identifier: Apache-2.0

#
# Module manifest for module 'TierLevelIsolation'
#
# Generated by: Andreas Lucas
#
# Generated on: 3/20/2025
#

@{
    

    # Script module or binary module file associated with this manifest.
    RootModule = '0.1\TierLevelIsolation.psm1'
    
    # Version number of this module.
    ModuleVersion = '0.1.20261003.1'
    
    # Supported PSEditions
    # CompatiblePSEditions = @()
    
    # ID used to uniquely identify this module
    GUID = '32c51271-3735-4b61-b80f-7284dafe6c77'
    
    # Author of this module
    Author = 'Andreas Lucas'
    
    # Company or vendor of this module
    CompanyName = ''
    
    # Copyright statement for this module
    Copyright = 'Copyright 2024-2026 Andreas Lucas and contributors. Licensed under Apache License 2.0.'
    
    # Description of the functionality provided by this module
    Description = 'This module provides configuration methods for the Kerberos Authentication Policy based Tier Level isolation'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'
    
    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @("ActiveDirectory")
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
                            "Add-TierLevelIsolationComputerPath",
                            "Add-TierLevelIsolationDomain",
                            "Add-TierLevelIsolationGroup",
                            "Add-TierLevelIsolationServiceAccountPath",
                            "Add-TierLevelIsolationUserPath",
  
                            "Get-TierLevelIsolationConfiguration",
                            "Get-TierLevelIsolationGroup",
                            "Get-DebugLogPath",
  
                            "Remove-TierLevelIsolationComputerPath",
                            "Remove-TierLevelIsolationDomain",
                            "Remove-TierLevelIsolationGroup",
                            "Remove-TierLevelIsolationServiceAccountPath",
                            "Remove-TierLevelIsolationUserPath",

                            "Set-TierLevelIsolationComputerGroup",
                            "Set-DebugLogPath",
                            "Set-TierLevelPrivilegedGroupsCleanUpState",  
                            "Set-TierLevelIsolationKerberosAuthenticationPolicy",
                            "Set-TierLevelIsolationScope",
                            "Set-TierLevelProtectedUsersState"
)
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()
    
    # Variables to export from this module
    #VariablesToExport = ''
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    #AliasesToExport = @()
    
    # DSC resources to export from this module
    # DscResourcesToExport = @()
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    # FileList = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ActiveDirectory','Kerberos','TierModel','Security','Authentication','KerberosPolicy')

        # ActiveDirectory is provided by Windows RSAT and is not published to PSGallery.
        ExternalModuleDependencies = @('ActiveDirectory')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Kili69/TierLevelIsolation/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Kili69/TierLevelIsolation'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Relicensed the project under Apache License 2.0 and moved the project disclaimer to README.md.'
        
        RequireLicenseAcceptance = $false

    } # End of PSData hashtable

} # End of PrivateData hashtable
    
    } 
    # End of hashtable